### ISSUE TITLE
Login failing with security key

### ISSUE THREAD

**Issue by maddler** [Decad3nce/trunks-public#58]
While trying to access my account with a security key I get redirected to an error page: "the reqyest you submitted was invalid or malformed".

Steps to reproduce:

1. select your instance
2. insert username and passowrd
3. select "use security key"

Result: error page being shown. 
Additionally, if seleciting the 2FA option in step, doesn't look to be doing anything

Expected result: the page/option for security key validation gets raised.

OS: Android 13 on Oneplus 10pro. 
App: 1.1.2

**Comment by Decad3nce** [comment]
Unfortunately security keys (through usb) are only accessible in custom tabs for oauth afaict. 

see https://chromium.googlesource.com/chromium/src/+/df9b02ecdd6ddcf299ad5f9e9eb7132f101831bd

Since firefox does a terrible job in rerouting oauth redirects for applications on mobile, I'm stuck with using an in app webview to do oauth. 

Original firefox issue: https://github.com/Decad3nce/trunks-public/issues/5#issuecomment-1407793233

My only options are:

1. Add an option for users to use 'custom tabs' as their preferred login means, which would allow a user to go through chrome/safari and have the support of usb security key input.
2. Just not support it; which seems to be the case with tusky and a few other android apps I've tested - no clue for iOS.

I hate all of these options - I'm really frustrated with firefox and their inability to entrust the concepts of applinks redirects; that decision directly weakens the overall security model of oauth flows for mobile clients and puts an undue burden on developers to work around their benevolent decision making. 

It's even worse since this bug seems years old and ignored by mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809264

**Comment by Decad3nce** [comment]
I went with option 1. I verified I can login with a security key if I check the option for "Use external browser to login"

**Comment by maddler** [comment]
3 is definitely a no-go.
2 is tempting, but wouldn't address the issue.
1 seems reasonable, unless you can't force Chrome/Safari to be use, regardless of the default browser being used?
